#!/bin/sh
# bootstrap.sh -- thread bootstrap for the playbook.
# Usage: bootstrap.sh <project> [sha]
#
# Performs ONE sparse clone of the shared repository containing the
# playbook plus the named project directory, checked out AT the
# recorded SHA (given, or resolved from the default branch), writes
# the SHA and the project's render stamp into a kickoff skeleton
# stub, and prints the paste-ready block for plain (Tier C) chats.
# The recorded SHA is ground truth: the checkout IS that SHA, not a
# note about it (ADR-004).
#
# Repository location comes from, in order: $PLAYBOOK_REPO_URL, or
# the origin remote of the repository containing the current
# directory. The URL is never hardcoded here (promotion safety).
# Idempotent: rerunning with the same project and SHA reuses the
# existing checkout and reprints the same block.
# ASCII only. POSIX sh.

set -u

[ $# -ge 1 ] || { echo "usage: bootstrap.sh <project> [sha]" >&2; exit 2; }
PROJECT="$1"
SHA="${2:-}"

REPO_URL="${PLAYBOOK_REPO_URL:-$(git config --get remote.origin.url 2>/dev/null || true)}"
[ -n "$REPO_URL" ] || {
  echo "bootstrap.sh: set PLAYBOOK_REPO_URL or run inside a clone" >&2
  exit 1; }

# --- clone or reuse ---------------------------------------------------
short() { printf '%s' "$1" | cut -c1-8; }

if [ -n "$SHA" ]; then
  DIR="${PROJECT}-at-$(short "$SHA")"
else
  DIR="${PROJECT}-bootstrap"
fi

if [ -d "$DIR/.git" ]; then
  HEAD_NOW="$(git -C "$DIR" rev-parse HEAD)"
  if [ -n "$SHA" ] && [ "$HEAD_NOW" != "$SHA" ]; then
    echo "bootstrap.sh: $DIR exists at $HEAD_NOW, not $SHA; remove it or pick another SHA" >&2
    exit 1
  fi
  SHA="$HEAD_NOW"
else
  git clone --quiet --filter=blob:none --sparse "$REPO_URL" "$DIR" \
    || git clone --quiet --sparse "$REPO_URL" "$DIR" \
    || { echo "bootstrap.sh: clone failed" >&2; exit 1; }
  git -C "$DIR" sparse-checkout set llm_playbook "$PROJECT"
  if [ -n "$SHA" ]; then
    git -C "$DIR" checkout --quiet "$SHA" \
      || { echo "bootstrap.sh: checkout of $SHA failed" >&2; exit 1; }
  else
    SHA="$(git -C "$DIR" rev-parse HEAD)"
  fi
fi

[ -d "$DIR/$PROJECT" ] || \
  echo "bootstrap.sh: warning: project directory $PROJECT absent at $SHA" >&2

# --- gather stamp and version -----------------------------------------
VERSION="$(cat "$DIR/llm_playbook/VERSION" 2>/dev/null || echo unknown)"
RENDER="$DIR/$PROJECT/CONTEXT.md"
if [ -f "$RENDER" ]; then
  STAMP="$(sed -n '2p' "$RENDER")"
else
  STAMP="no render found at $PROJECT/CONTEXT.md (render one per render.md)"
fi

# --- kickoff skeleton stub --------------------------------------------
STUB="$DIR/kickoff-$PROJECT-$(short "$SHA").md"
{
  echo "KICKOFF STUB -- generated by bootstrap.sh; complete the"
  echo "FILL-IN lines from the project's STATUS.md, then paste."
  echo ""
  echo "THREAD: <PROJ-ROLE-NNN per naming.md>  ROLE: <DESIGN|IMPL|CAPTURE>"
  echo "playbook: v$VERSION at $SHA (checked out, read-only)"
  echo "render stamp: $STAMP"
  echo "state the stamp you see above; mismatch is a finding."
  echo ""
  echo "FILL-IN from STATUS.md:"
  echo "  baseline / green count: <FILL-IN>"
  echo "  branch: <FILL-IN>"
  echo "  open forks: <FILL-IN>"
  echo "  this thread's task: <FILL-IN>"
  echo ""
  echo "SCOPE RULE: if implementation reveals the fix is trivial,"
  echo "absorb it without re-kickoff; if design reveals scope beyond"
  echo "this thread, flag a CANDIDATE NEW THREAD -- do not extend."
} > "$STUB"

# --- paste-ready block -------------------------------------------------
echo "=== paste-ready block (Tier C) ==="
cat "$STUB"
echo "=== end block (stub saved at $STUB) ==="
exit 0
