---
title: "Development Log of cv_in_quarto"
date: 2025-06-08
---

# Intro

Write down notes, ideas, thoughts while working on the small cv_in_quarto project.
Notes are split by day.

## 2025-06-08
Was considering doing it manually but wanted to see if GPT4o could create a template based on the picture. To achieve this, I took a screenshot, used illustrator to crop and then just told GPT, via the web interface, to give me a template.
That is the basis of the first version of the file.

Encountered the error that Arial was not available. Solved pretty easily by install a package.
Now there are some problems with some characters displaying but I think I can add all of the content first and then start mucking with the quarto features
Just had to set the encoding to utf8.

### Underlining
Tried multiple things for underlining a section.
```{quarto}
format:
  pdf:
    include-in-header:
      text: |
        \usepackage{ulem} % For custom underlining
        \newcommand{\fullunderline}[1]{%
          \noindent\makebox[\linewidth]{\uline{#1}}%
        }
## \fullunderline{Summary}

::: {.full-underline}
## Summary
:::

This is the only one that did what I wanted.
```{=latex}
\section*{\underline{\makebox[\linewidth][l]{Summary}}}
```
```
```
Now I used the first mode to add underline to a particular text. Turns out ulem centers by default and turns the markdown way to italicize into underline.
Add [l] after [\linewidth] to align left.
Add normalem option to restore italics or use latex command \textit{}.

Also the following regex would be useful to move between underscore surrounded words: _\w\+ \+\w\+
Managed to replace all of them straightforwardly using a register and macro along with a search for exactly three hashes (/#\{3}).

Using the fullunderline custom command caused the whole line to be taken up (because of makebox). Shifted to \uline{} command which does what I want. Remove the fullunderline command from the header. Nice.
While wrapping all of the instances using a macro, realized I could have used substitution.
```{vim}
:%s//\\uline{&}/g
```
Also the ulem package is required for ulem.

### Spacing
Set spacing in header to 0 was too much.
```{quarto}
% Reduce paragraph spacing
    \setlength{\parskip}{0pt}  % No space between paragraphs
    \setlength{\parindent}{0pt}  % No paragraph indentation
```
Set line break with two spaces and newline. Add \vspace{-1.3em} selectively. Add \vspace the the cvsection command.
Always do a crazy number first to see effect then adjust.

### title
Disable by removing the title. Add manually and control spacing.

Think that about does it. Basically replicated the word document at this point. Mostly need to adjust the actual content.

## 2025-06-10
Tried a few things to remove the header but geometry parameter in the yaml was the simplest.
I would like to enhance the content but not sure how to handle a bunch of files. Either have many cvs, git worktrees or something else?
I think I will use worktrees.

```{bash}
cd ~/explorations
mkdir -p ../cv_worktrees
git checkout -b cv_summary
git checkout -b cv_remove_summary

git worktree add ../cv_worktrees/cv_summary cv_summary
git worktree add ../cv_worktrees/cv_remove_summary cv_remove_summary
```
To render all and see I can use a small script render_all.sh to take care of that and then just use view_files -t to plot the all or refresh after they are loaded.

Create a simple set of scripts to help with working the worktrees.
